spring.application.name=demo

# =====================
# SECURITY (DEV ONLY)
# =====================
spring.security.user.name=tharun
spring.security.user.password=Tharunk043

# =====================
# MYSQL (JPA)
# =====================

spring.data.mongodb.uri=mongodb+srv://tharunvelamakuru143:Tharunk043@tharundb.lm8v99q.mongodb.net/mydb?retryWrites=true&w=majority
spring.data.mongodb.database=mydb


server.port=8080

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB


# =====================
# JPA
# =====================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# =====================
# ACTUATOR
# =====================
management.endpoints.web.exposure.include=health,info,metrics,env,beans

# =====================
# REDIS CACHE
# =====================
spring.cache.type=redis
spring.data.redis.host=causal-duck-21602.upstash.io
spring.data.redis.port=6379
spring.data.redis.ssl.enabled=true
spring.data.redis.timeout=10s
spring.data.redis.password={REDIS_PASSWORD}
