spring.application.name=demo

# =====================
# SECURITY (DEV ONLY)
# =====================
spring.security.user.name=tharun
spring.security.user.password=Tharunk043

# =====================
# MYSQL (JPA)
# =====================

spring.data.mongodb.uri=mongodb+srv://tharunvelamakuru143:Tharunk043@tharundb.lm8v99q.mongodb.net/mydb?retryWrites=true&w=majority
spring.data.mongodb.database=mydb


server.port=8080

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB


# =====================
# JPA
# =====================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# =====================
# ACTUATOR
# =====================
management.endpoints.web.exposure.include=health,info,metrics,env,beans

# =====================
# REDIS CACHE
# =====================
spring.cache.type=redis
spring.data.redis.host=${SPRING_REDIS_HOST:redis}
spring.data.redis.port=${SPRING_REDIS_PORT:6379}
spring.data.redis.ssl.enabled=${SPRING_REDIS_SSL_ENABLED:false}
spring.data.redis.timeout=${SPRING_REDIS_TIMEOUT:15s}
spring.data.redis.password=${REDIS_PASSWORD:}

# =========================
# REDPANDA KAFKA CONFIG (PROD)
# =========================
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.properties.security.protocol=${KAFKA_SECURITY_PROTOCOL:SASL_SSL}
spring.kafka.properties.sasl.mechanism=${KAFKA_SASL_MECHANISM:SCRAM-SHA-256}
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";

# Producer Config
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Consumer Config
spring.kafka.consumer.group-id=shoplive-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.listener.auto-startup=false
# =====================
# STRIPE PAYMENT
# =====================
stripe.secret.key=${STRIPE_SECRET_KEY}
